# Rust formatting configuration
# https://rust-lang.github.io/rustfmt/

edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"

# Imports
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true

# Comments
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true

# Functions
fn_single_line = false
fn_args_layout = "Tall"

# Structs
struct_lit_single_line = true
